### PR TITLE
Highlight unused function argument name as Comment

### LINKED ISSUE #6: Discussion/Feature: highlight unused function argument as comment
Since gleam supports prefixing an argument with underscore to mark it as unused it would be nice if the variable was highlighted like a comment.
The Elixir plugin [vim-elixir](https://github.com/elixir-editors/vim-elixir) does exactly that.

I hacked something together with my non existing vim regex skills:
Bildschirmfoto vom 2021-03-08 19-26-52
Bildschirmfoto vom 2021-03-08 19-27-17

What's the general opinion on this?

### PR DESCRIPTION
**Pull request by Simerax**
Supposed to fix: #6 

looks something likes this:
Bildschirmfoto vom 2021-03-09 01-13-07

### CODE REVIEW

**Comment by Simerax** [comment]
I just realized it breaks on Functions Argument Types which contain parenthesis since `gleamType` is not aware of them.
Ill convert this PR to a draft and take a look tomorrow.
Bildschirmfoto vom 2021-03-09 01-24-28

**Comment by Simerax** [comment]
okay I tried now for some time. I can't figure out how to make nested types work.
I managed to get simple types like `List(String)` to work but only because I hardcoded the first recursion of `gleamType` (change not commited). 
I don't really have the skills to make this work for infinite nested types.

This also looked a little odd because parenthesis got highlighted as well.
Bildschirmfoto vom 2021-03-09 19-36-42

The main issue is that the `gleamFunctionArguments` is a region which starts with `(` and ends with `)`. The parenthesis in the argument type break this region. 

@lpil do you have any idea on how to make this work?

**Comment by lpil** [comment]
> @lpil do you have any idea on how to make this work?

I do not I'm afraid :(

**Comment by Simerax** [comment]
I will close this pr for now and just keep the issue around. Maybe someone with the right skills finds the time to work on it. I think for advanced features like this the whole syntax definition would need a rewrite.

**Pull request closed without merging**
